{% set name = "topicgen" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10,<3.13
    - poetry-core
  run:
    - python >=3.10,<3.13
    - numpy
    - torch
    - transformers
    - gradio
    - aiohttp
    - python-dotenv
    - ruff
    - tiktoken
    - protobuf
    - sentencepiece
    - tokenizers

test:
  imports:
    - topicgen
    - transformers

about:
  home: https://github.com/Namgyu-Youn/topicgen
  license: MIT
  license_file: LICENSE
  summary: "topicgen: Generate related topics('#') by analyzing your source code."
  doc_url: https://github.com/Namgyu-Youn/topicgen
  dev_url: https://github.com/Namgyu-Youn/topicgen

extra:
  recipe-maintainers:
    - Namgyu-Youn