[tool.poetry]
name = "github-tag-generator"
version = "0.1.1"
description = ""
authors = ["Namgyu-Youn <yynk2012@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
gradio = "^5.9.1"
torch = "^2.5.1"
transformers = "^4.47.1"
aiohttp = "^3.11.11"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
