[tool.poetry]
name = "tag-generator"
version = "0.1.0"
description = ""
authors = ["Namgyu-Youn <yynk2012@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.34.0"
aiohttp = "^3.11.11"
gradio = "^5.9.1"
fastapi = "^0.115.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
