name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Validate Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry env use python${{ matrix.python-version }}
        poetry check
        poetry lock --check

    - name: Validate Dockerfile
      run: docker build . --file Dockerfile